      - name: Commit and Push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add api.csv
          git commit -m "Auto update api.csv" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git push
